#!/usr/bin/expect -f

set timeout $env(VPNTIMEOUT)

spawn -ignore HUP "/opt/forticlient-sslvpn/64bit/forticlientsslvpn_cli" --server $env(VPNADDR) --vpnuser $env(VPNUSER) --keepalive

# Send command
expect -exact "Password for VPN:"
send -- "$env(VPNPASS)\r"

expect -exact "STATUS::Connecting..."

# In case of invalid certificate
expect -exact "Would you like to connect to this server? (Y/N)" {
  send -- "Y\r"
}
